import type { App, Deal } from "@/types/store";

const sampleReviews1: App["reviews"] = [
  { id: "r1", userName: "Alex F.", rating: 5, title: "Exactly what we needed", content: "Clean dashboard, easy to connect our tools. Support was fast.", date: "2025-02-10", helpful: 12, verified: true },
  { id: "r2", userName: "Jordan M.", rating: 4, content: "Solid analytics. Would love more export options.", date: "2025-02-08", helpful: 5 },
  { id: "r3", userName: "Sam K.", rating: 5, title: "Great for startups", content: "Pricing is fair and the trial let us test everything.", date: "2025-02-05", helpful: 8, verified: true },
];
const sampleReviews2: App["reviews"] = [
  { id: "r4", userName: "Casey L.", rating: 4, title: "Simple and effective", content: "CRM without the bloat. Our team adopted it in a week.", date: "2025-02-12", helpful: 3 },
  { id: "r5", userName: "Riley T.", rating: 5, content: "Beta has been stable. Excited for the full launch.", date: "2025-02-09", helpful: 11, verified: true },
];

export const mockApps: App[] = [
  {
    id: "app-1",
    type: "app",
    name: "GrowthMetrics",
    description: "Track signups, revenue, and engagement in one dashboard.",
    longDescription: "GrowthMetrics gives growth teams a single place to track signups, revenue, and engagement. Connect your tools (Stripe, Segment, analytics) and see funnels, cohort retention, and revenue metrics in one dashboard.\n\nWe built it for startups and SMBs who need clarity without the complexity of enterprise BI. Start with a 30-day free trial—no credit card required.",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=240&fit=crop",
    screenshots: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=500&fit=crop",
    ],
    videos: ["https://www.youtube.com/embed/jNQXAC9IVRw"],
    publisher: {
      id: "p1",
      name: "Metric Labs",
      verified: true,
      about: "Metric Labs is a B2B analytics startup focused on helping growth teams measure what matters. We're a team of 12 based in San Francisco, backed by Y Combinator.",
      website: "https://metriclabs.io",
    },
    usersCount: 1240,
    dealsCount: 2,
    category: "Analytics",
    badges: ["New", "Featured"],
    createdAt: "2025-02-01",
    appType: "trial",
    trialPeriod: "30 days",
    pricing: "$29/mo",
    rating: 4.8,
    ratingCount: 312,
    reviews: sampleReviews1,
    features: ["Lead Management", "Email Integration", "AI Insights", "Pipeline Management"],
    downloads: 12400,
    version: "2.1.0",
    lastUpdated: "2025-02-15",
    size: "—",
    languages: ["English"],
    ageRating: "4+",
    inAppPurchase: false,
    copyright: "© 2025 Metric Labs, Inc.",
    website: "https://metriclabs.io",
    privacyPolicyUrl: "https://metriclabs.io/privacy",
    platforms: ["Web"],
    whatsNew: [
      { version: "2.1.0", date: "2025-02-15", notes: ["New funnel visualization", "Faster report exports", "Bug fixes and performance improvements"] },
      { version: "2.0.0", date: "2025-02-01", notes: ["Redesigned dashboard", "Slack integration", "API v2"] },
    ],
    distributionOptions: [
      { type: "app-store", url: "https://apps.apple.com/app/growthmetrics/id123456789" },
      { type: "play-store", url: "https://play.google.com/store/apps/details?id=io.growthmetrics" },
    ],
  },
  {
    id: "app-2",
    type: "app",
    name: "LaunchPad CRM",
    description: "Simple CRM for early-stage startups and small teams.",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=240&fit=crop",
    publisher: {
      id: "p2",
      name: "Startup Tools Inc",
      about: "Startup Tools Inc builds software for early-stage companies. LaunchPad CRM is our flagship product, designed for teams under 50.",
      website: "https://startuptools.io",
    },
    usersCount: 890,
    dealsCount: 1,
    category: "Productivity",
    badges: ["New"],
    createdAt: "2025-02-10",
    appType: "beta",
    seekingBetaTesters: true,
    launchInfo: { betaUsers: 420, maxBetaUsers: 1000 },
    trialPeriod: "Free during beta",
    pricing: "Free during beta, $49/mo after",
    rating: 4.6,
    ratingCount: 128,
    reviews: sampleReviews2,
    features: ["Channels", "Video Calls", "File Sharing", "Integrations"],
    downloads: 4200,
    version: "0.9.2",
    lastUpdated: "2025-02-14",
    size: "—",
    languages: ["English", "Spanish"],
    ageRating: "4+",
    inAppPurchase: false,
    copyright: "© 2025 Startup Tools Inc.",
    website: "https://startuptools.io",
    platforms: ["Web", "iOS", "Android"],
    whatsNew: [
      { version: "0.9.2", date: "2025-02-14", notes: ["Video call quality improvements", "New file previews"] },
      { version: "0.9.0", date: "2025-02-10", notes: ["Public beta launch", "Invite by link"] },
    ],
    distributionOptions: [
      { type: "play-store", url: "https://play.google.com/store/apps/details?id=io.launchpad.crm" },
      { type: "direct", url: "https://startuptools.io/launchpad/LaunchPad-CRM.apk", label: "Download APK" },
    ],
  },
  {
    id: "app-3",
    type: "app",
    name: "DealFlow",
    description: "Create and manage limited-time offers for your users.",
    longDescription: "DealFlow helps you create and manage limited-time offers, coupons, and campaigns. Run flash sales, referral discounts, and partner deals from one platform. Integrates with your checkout and marketing tools.",
    imageUrl: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=400&h=240&fit=crop",
    screenshots: [
      "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=800&h=500&fit=crop",
    ],
    videos: [],
    publisher: {
      id: "p3",
      name: "GrowthLab",
      verified: true,
      about: "GrowthLab is the platform for startup growth. We run apps, deals, and community programs.",
      website: "https://growthlab.com",
    },
    usersCount: 2100,
    dealsCount: 5,
    category: "Marketing",
    badges: ["Featured"],
    createdAt: "2024-12-15",
    appType: "trial",
    trialPeriod: "21 days",
    pricing: "$49/mo",
    rating: 4.9,
    ratingCount: 445,
    features: ["Email Campaigns", "Social Scheduling", "Lead Scoring", "A/B Testing"],
    downloads: 18500,
    version: "3.2.0",
    lastUpdated: "2025-02-12",
    size: "—",
    languages: ["English", "French", "German"],
    ageRating: "4+",
    inAppPurchase: true,
    copyright: "© 2024 GrowthLab.",
    website: "https://growthlab.com",
    platforms: ["Web"],
    whatsNew: [
      { version: "3.2.0", date: "2025-02-12", notes: ["New A/B test templates", "Slack alerts"] },
    ],
    distributionOptions: [
      { type: "web", url: "https://app.dealflow.io", label: "Open web app" },
      { type: "app-store", url: "https://apps.apple.com/app/dealflow/id987654321" },
      { type: "play-store", url: "https://play.google.com/store/apps/details?id=io.dealflow" },
    ],
  },
  {
    id: "app-4",
    type: "app",
    name: "DataPilot Analytics",
    description: "Real-time analytics and reporting. We're looking for pilot teams to shape the product.",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=240&fit=crop",
    publisher: {
      id: "p4",
      name: "DataFlow Solutions",
      about: "DataFlow builds real-time analytics for product and growth teams.",
    },
    usersCount: 156,
    dealsCount: 0,
    category: "Analytics",
    badges: ["New"],
    createdAt: "2025-02-05",
    appType: "pilot",
    seekingPilotUsers: true,
    launchInfo: { pilotSlots: 50, pilotSlotsFilled: 18 },
    trialPeriod: "Pilot program – 3 months",
    pricing: "Free during pilot",
    rating: 4.7,
    ratingCount: 28,
    features: ["Real-time Data", "Custom Dashboards", "Export Reports", "AI Predictions"],
    downloads: 156,
    version: "0.5.0",
    lastUpdated: "2025-02-10",
    size: "—",
    languages: ["English"],
    ageRating: "4+",
    inAppPurchase: false,
    copyright: "© 2025 DataFlow Solutions.",
    whatsNew: [{ version: "0.5.0", date: "2025-02-10", notes: ["Pilot release", "Dashboard v1"] }],
    distributionOptions: [
      { type: "web", url: "https://analytics.dataflow.io" },
      { type: "huawei", url: "https://appgallery.huawei.com/app/C123456789" },
    ],
  },
  {
    id: "app-5",
    type: "app",
    name: "ValidateAI",
    description: "AI-powered customer insights. Join our validation program and get early access.",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=240&fit=crop",
    publisher: { id: "p5", name: "AI Labs", about: "AI Labs builds AI-powered tools for customer and market insights." },
    usersCount: 89,
    dealsCount: 0,
    category: "AI",
    badges: ["New"],
    createdAt: "2025-02-12",
    appType: "validation",
    seekingValidationUsers: true,
    launchInfo: {
      validationGoal: "Test market fit with 500 early adopters",
      progress: 42,
      goals: ["500 active users", "4.5+ rating", "10K insights generated"],
    },
    trialPeriod: "Unlimited during validation",
    pricing: "Free during validation",
    rating: 4.5,
    ratingCount: 18,
    features: ["Natural language queries", "Multi-language", "Analytics dashboard"],
    downloads: 89,
    version: "0.3.0",
    lastUpdated: "2025-02-12",
    languages: ["English"],
    ageRating: "4+",
    inAppPurchase: false,
    copyright: "© 2025 AI Labs.",
    whatsNew: [{ version: "0.3.0", date: "2025-02-12", notes: ["Validation program launch"] }],
  },
  {
    id: "app-6",
    type: "app",
    name: "TeamSync",
    description: "All-in-one team collaboration. Beta testers get 6 months free.",
    imageUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=240&fit=crop",
    publisher: { id: "p6", name: "TeamConnect", about: "TeamConnect makes collaboration simple for distributed teams." },
    usersCount: 534,
    dealsCount: 1,
    category: "Productivity",
    badges: ["Featured"],
    createdAt: "2024-11-01",
    appType: "beta",
    seekingBetaTesters: true,
    launchInfo: { betaUsers: 534, maxBetaUsers: 800 },
    trialPeriod: "Free during beta",
    pricing: "Free during beta, $19/mo after",
    rating: 4.8,
    ratingCount: 89,
    features: ["Channels", "Video Calls", "File Sharing", "Screen Sharing"],
    downloads: 5340,
    version: "1.0.0-beta",
    lastUpdated: "2025-02-11",
    languages: ["English", "Spanish", "Portuguese"],
    ageRating: "4+",
    inAppPurchase: true,
    copyright: "© 2024 TeamConnect.",
    platforms: ["Web", "iOS", "Android"],
    whatsNew: [{ version: "1.0.0-beta", date: "2025-02-11", notes: ["Beta 2", "Mobile apps"] }],
  },
];

export const mockDeals: Deal[] = [
  {
    id: "deal-1",
    type: "deal",
    title: "50% off first year",
    description: "Get half off your first year of GrowthMetrics Pro. Use at checkout.",
    imageUrl: "https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=400&h=240&fit=crop",
    appId: "app-1",
    appName: "GrowthMetrics",
    publisher: { id: "p1", name: "Metric Labs", verified: true },
    discount: "50% off",
    dealType: "discount",
    category: "Analytics",
    badges: ["Deal", "Limited time"],
    createdAt: "2025-02-15",
    couponCode: "GROWTH50",
    deadline: "2025-03-31",
  },
  {
    id: "deal-2",
    type: "deal",
    title: "Free trial extended to 30 days",
    description: "Try LaunchPad CRM free for 30 days, no card required.",
    imageUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=240&fit=crop",
    appId: "app-2",
    appName: "LaunchPad CRM",
    publisher: { id: "p2", name: "Startup Tools Inc" },
    discount: "30 days free",
    dealType: "free_trial",
    category: "Productivity",
    badges: ["Deal"],
    createdAt: "2025-02-12",
  },
  {
    id: "deal-3",
    type: "deal",
    title: "$100 in free credits",
    description: "New users get $100 in platform credits to run campaigns. No credit card needed to start.",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=240&fit=crop",
    appId: "app-1",
    appName: "GrowthMetrics",
    publisher: { id: "p1", name: "Metric Labs", verified: true },
    discount: "$100 credits",
    dealType: "credits",
    category: "Marketing",
    badges: ["Deal", "Limited time"],
    createdAt: "2025-02-10",
    couponCode: "CREDITS100",
  },
  {
    id: "deal-4",
    type: "deal",
    title: "Free download – Starter template pack",
    description: "Download our Starter template pack for free. Includes 10 ready-to-use dashboards and reports.",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=240&fit=crop",
    appId: "app-3",
    appName: "DealFlow",
    publisher: { id: "p3", name: "GrowthLab" },
    discount: "Free download",
    dealType: "free_download",
    category: "Productivity",
    badges: ["Deal"],
    createdAt: "2025-02-08",
  },
  {
    id: "deal-5",
    type: "deal",
    title: "Analytics + CRM bundle",
    description: "Get GrowthMetrics and LaunchPad CRM together for the price of one. Limited spots.",
    imageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=240&fit=crop",
    appId: "app-1",
    appName: "GrowthMetrics",
    publisher: { id: "p1", name: "Metric Labs", verified: true },
    discount: "2 for 1 bundle",
    dealType: "bundle",
    category: "Business",
    badges: ["Deal", "Limited time"],
    createdAt: "2025-02-05",
    couponCode: "BUNDLE2X1",
  },
];

export const allListings = [...mockApps, ...mockDeals];

/** Apps that are seeking beta testers, pilot users, or validation participants */
export function getAppsSeekingTesters(apps: App[]): App[] {
  return apps.filter(
    (a) => a.seekingBetaTesters || a.seekingPilotUsers || a.seekingValidationUsers
  );
}
